import { User, Book, Purchase, VisitorRecord, Bookmark, ReadingHistory, Payment } from '@digital-library/types';
import bcrypt from 'bcryptjs';

// Pre-seeded User Data
const defaultPasswordHash = bcrypt.hashSync('Password123!', 10);

export let usersStore: User[] = [
  {
    id: 'user-admin-1',
    name: 'Dr. Sarah Connor (Admin)',
    email: 'admin@university.edu',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    role: 'ADMIN',
    provider: 'local',
    isBlocked: false,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Alex Rivera',
    email: 'alex.rivera@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    role: 'USER',
    provider: 'google',
    isBlocked: false,
    createdAt: '2026-02-14T10:15:00Z',
  },
  {
    id: 'user-3',
    name: 'Elena Rostova',
    email: 'elena.rostova@outlook.com',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    role: 'USER',
    provider: 'microsoft',
    isBlocked: false,
    createdAt: '2026-03-01T12:30:00Z',
  },
  {
    id: 'user-4',
    name: 'Marcus Vance',
    email: 'marcus.vance@icloud.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    role: 'USER',
    provider: 'apple',
    isBlocked: false,
    createdAt: '2026-03-12T14:20:00Z',
  },
  {
    id: 'user-5',
    name: 'Sophia Chen',
    email: 'sophia.chen@meta.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    role: 'USER',
    provider: 'facebook',
    isBlocked: false,
    createdAt: '2026-04-05T09:45:00Z',
  },
];

export const userPasswordsMap: Record<string, string> = {
  'admin@university.edu': defaultPasswordHash,
  'alex.rivera@gmail.com': defaultPasswordHash,
};

// Pre-seeded Paid eBook Library Data
export let booksStore: Book[] = [
  {
    id: 'book-1',
    title: 'Quantum Computing Foundations & Architecture',
    author: 'Prof. David E. Kipping',
    category: 'Computer Science & Physics',
    price: 49.99,
    coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600',
    pdfUrl: '/uploads/sample-quantum.pdf',
    description: 'A comprehensive guide to quantum mechanics, qubit logic gates, fault-tolerant algorithms, and modern quantum computing hardware systems.',
    totalPages: 8,
    rating: 4.9,
    pagesText: [
      'CHAPTER 1: Introduction to Quantum Bits\n\nQuantum computing represents a paradigm shift from classical digital computation. Unlike classical bits that exist in state 0 or 1, qubits utilize superposition |ψ⟩ = α|0⟩ + β|1⟩.',
      'CHAPTER 1 (Cont.): Hilbert Spaces & Bloch Sphere\n\nThe geometrical representation of pure qubit states on a unit 2-sphere known as the Bloch Sphere allows intuitive visualization of unitary gate transformations.',
      'CHAPTER 2: Quantum Logic Gates\n\nSingle qubit rotations including Hadamard (H), Pauli-X, Pauli-Y, and Pauli-Z gates form the backbone of quantum circuit design.',
      'CHAPTER 2 (Cont.): Entanglement & CNOT Gate\n\nControlled-NOT gates generate non-local EPR pair states: |Φ+⟩ = 1/√2 (|00⟩ + |11⟩), enabling quantum teleportation algorithms.',
      'CHAPTER 3: Grover\'s Search Algorithm\n\nGrover\'s algorithm provides quadratic speedup for unstructured database query problems in O(√N) time complexity.',
      'CHAPTER 3 (Cont.): Phase Inversion & Diffusion\n\nThe amplitude amplification process iteratively reflects state vectors about the mean amplitude to isolate target search keys.',
      'CHAPTER 4: Quantum Error Correction\n\nShor 9-qubit codes and surface codes protect logical qubits against phase flip and bit flip decoherence in noisy intermediate-scale quantum (NISQ) systems.',
      'CHAPTER 5: Future Horizons in Quantum AI\n\nHybrid quantum-classical algorithms such as Variational Quantum Eigensolver (VQE) revolutionize molecular simulation and material design.',
    ],
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'book-2',
    title: 'Advanced Neural Networks & Deep Learning',
    author: 'Dr. Katherine Thorne',
    category: 'Artificial Intelligence',
    price: 59.99,
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600',
    pdfUrl: '/uploads/sample-neural.pdf',
    description: 'Master attention mechanisms, transformer architectures, backpropagation mathematics, and large language model pre-training strategies.',
    totalPages: 6,
    rating: 4.95,
    pagesText: [
      'CHAPTER 1: Backpropagation Mathematics\n\nGradient descent optimization computes partial derivatives ∂L/∂w via chain rule across multi-layer perceptron computational graphs.',
      'CHAPTER 2: Convolutional Neural Networks\n\nSpatial invariant feature extractors using receptive fields, stride sliding windows, and max pooling operations in image processing.',
      'CHAPTER 3: Self-Attention Mechanics\n\nQuery, Key, and Value matrices compute contextual attention weights: Attention(Q,K,V) = softmax(QK^T / √d_k) V.',
      'CHAPTER 4: Transformer Architecture\n\nMulti-head attention blocks stacked with layer normalization and residual connections drive state-of-the-art vision and language models.',
      'CHAPTER 5: Generative Adversarial Networks\n\nMinimax game dynamics between Generator G and Discriminator D: min_G max_D V(D,G).',
      'CHAPTER 6: Model Quantization & Deployment\n\nOptimizing FP32 model parameters into INT8 representations for ultra-low latency edge inferencing.',
    ],
    createdAt: '2026-02-01T11:30:00Z',
  },
  {
    id: 'book-3',
    title: 'History of Global Academic Libraries (1750–2025)',
    author: 'Prof. Arthur Pendelton',
    category: 'History & Library Science',
    price: 34.50,
    coverImage: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600',
    pdfUrl: '/uploads/sample-history.pdf',
    description: 'An architectural and historical analysis of university archives, manuscript preservation, and the digital transformation of research libraries.',
    totalPages: 6,
    rating: 4.75,
    pagesText: [
      'CHAPTER 1: The Monastic Archives\n\nEarly university library collections relied on hand-copied manuscripts cataloged under specialized Dewey-style classification schemas.',
      'CHAPTER 2: The Gutenberg Revolution\n\nMovable type printing accelerated academic dissemination across European centers of learning in the 15th and 16th centuries.',
      'CHAPTER 3: The Birth of University Visitor Registers\n\nFormal physical guest logs recorded visiting scholars, keynote lecturers, and international researchers entering institutional archives.',
      'CHAPTER 4: Microfilm & Card Catalogs\n\nMid-20th century preservation technologies digitized fragile parchment papers into high-density storage films.',
      'CHAPTER 5: Digital Relational Databases\n\nThe introduction of Microsoft Access (.mdb) and relational SQL engines streamlined visitor records in the late 1990s.',
      'CHAPTER 6: The Modern Cloud Library\n\nOpen-access digital repositories enable global instant search, page flipping visualization, and AI semantic lookup.',
    ],
    createdAt: '2026-02-10T14:10:00Z',
  },
  {
    id: 'book-4',
    title: 'Lytton to Maulana Azad Library: Vision and Mission',
    author: 'Siddharth Mukherjee',
    category: 'Software Engineering',
    price: 44.99,
    coverImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600',
    description: 'Designing fault-tolerant microservices, consensus algorithms (Raft, Paxos), gRPC communication, and event-driven architectures.',
    totalPages: 5,
    rating: 4.88,
    pagesText: [
      'CHAPTER 1: Monolith vs Microservices\n\nDecomposing monolithic domains into bounded contexts improves continuous deployment velocity.',
      'CHAPTER 2: Consensus with Raft\n\nLeader election, log replication, and safety invariants in distributed consensus clusters.',
      'CHAPTER 3: Event Sourcing & CQRS\n\nSeparating read and write state models with immutable event streams powered by Apache Kafka.',
      'CHAPTER 4: API Gateway Pattern\n\nRate limiting, authentication, payload transformation, and circuit breaker patterns.',
      'CHAPTER 5: Zero-Downtime Deployment Strategies\n\nBlue-green releases and canary deployments in Kubernetes clusters.',
    ],
    createdAt: '2026-03-05T09:00:00Z',
  },
];

// Pre-seeded University Visitor Records (Simulated legacy MDB Access database entries)
export let visitorRecordsStore: VisitorRecord[] = [
  {
    id: 'vis-101',
    visitorName: 'Dr. Robert Oppenheimer',
    visitDate: '1954-04-12',
    purpose: 'Special Keynote Lecture on Theoretical Physics',
    department: 'Department of Physics & Astronomy',
    contact: 'roppenheimer@ias.edu',
    year: 1954,
    notes: 'Guest of Dean Harrison. Access granted to Special Collections Room B.',
    originalMdbId: 'MDB_REG_1954_001',
  },
  {
    id: 'vis-102',
    visitorName: 'Prof. Richard Feynman',
    visitDate: '1965-11-03',
    purpose: 'Quantum Electrodynamics Seminar',
    department: 'School of Science',
    contact: 'feynman@caltech.edu',
    year: 1965,
    notes: 'Signed university brass guest register. Consulted Feynman Diagrams archives.',
    originalMdbId: 'MDB_REG_1965_042',
  },
  {
    id: 'vis-103',
    visitorName: 'Dr. Margaret Hamilton',
    visitDate: '1969-07-22',
    purpose: 'Apollo Guidance Computer Software Exhibition',
    department: 'Computer Science & Engineering',
    contact: 'm.hamilton@mit.edu',
    year: 1969,
    notes: 'Donated original printed software stack listings to central library library.',
    originalMdbId: 'MDB_REG_1969_089',
  },
  {
    id: 'vis-104',
    visitorName: 'Sir Tim Berners-Lee',
    visitDate: '1991-09-18',
    purpose: 'World Wide Web Hypertext Protocol Demonstration',
    department: 'Information & Library Science',
    contact: 'timbl@cern.ch',
    year: 1991,
    notes: 'Demonstrated NeXT workstation web browser to university faculty.',
    originalMdbId: 'MDB_REG_1991_112',
  },
  {
    id: 'vis-105',
    visitorName: 'Dr. Linus Torvalds',
    visitDate: '1996-03-29',
    purpose: 'Linux Kernel 2.0 Open Source Workshop',
    department: 'Computer Science Department',
    contact: 'torvalds@helsinki.fi',
    year: 1996,
    notes: 'Keynote in Main Auditorium. Installed Linux on laboratory terminals.',
    originalMdbId: 'MDB_REG_1996_205',
  },
  {
    id: 'vis-106',
    visitorName: 'Prof. Ada Lovelace Scholar Foundation',
    visitDate: '2005-10-14',
    purpose: 'Historical Computing Archival Research',
    department: 'Digital Humanities Archive',
    contact: 'archive@lovelace-foundation.org',
    year: 2005,
    notes: 'Examined 19th-century Analytical Engine engine notes.',
    originalMdbId: 'MDB_REG_2005_341',
  },
  {
    id: 'vis-107',
    visitorName: 'Dr. Geoffrey Hinton',
    visitDate: '2012-06-08',
    purpose: 'Deep Convolutional Networks Symposium',
    department: 'AI & Data Science Institute',
    contact: 'hinton@cs.toronto.edu',
    year: 2012,
    notes: 'Presented ImageNet classification results.',
    originalMdbId: 'MDB_REG_2012_512',
  },
  {
    id: 'vis-108',
    visitorName: 'Dr. Yoshua Bengio',
    visitDate: '2018-04-20',
    purpose: 'Deep Learning Representation Learning Summit',
    department: 'MILA Research Lab',
    contact: 'bengio@mila.quebec',
    year: 2018,
    notes: 'Participated in panel discussion on generative models.',
    originalMdbId: 'MDB_REG_2018_670',
  },
  {
    id: 'vis-109',
    visitorName: 'Prof. Yann LeCun',
    visitDate: '2022-09-15',
    purpose: 'Energy-Based Models and Joint Embedding Architectures',
    department: 'Computer Science',
    contact: 'yann@nyu.edu',
    year: 2022,
    notes: 'Visited computer vision laboratory.',
    originalMdbId: 'MDB_REG_2022_890',
  },
  {
    id: 'vis-110',
    visitorName: 'Dr. Demis Hassabis',
    visitDate: '2024-03-10',
    purpose: 'AlphaFold 3 & Molecular Biology Keynote',
    department: 'Bioinformatics & AI Center',
    contact: 'demis@deepmind.com',
    year: 2024,
    notes: 'Visited library special collection on protein structure manuscripts.',
    originalMdbId: 'MDB_REG_2024_999',
  },
];

// Pre-seeded Purchases (Feeds Center Section: Latest 10 Recent Buyers)
export let purchasesStore: Purchase[] = [
  {
    id: 'purch-1',
    userId: 'user-2',
    userName: 'Alex Rivera',
    userEmail: 'alex.rivera@gmail.com',
    userAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    bookId: 'book-1',
    bookTitle: 'Quantum Computing Foundations & Architecture',
    bookCover: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600',
    amount: 49.99,
    paymentMethod: 'Google Pay',
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'purch-2',
    userId: 'user-3',
    userName: 'Elena Rostova',
    userEmail: 'elena.rostova@outlook.com',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    bookId: 'book-2',
    bookTitle: 'Advanced Neural Networks & Deep Learning',
    bookCover: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600',
    amount: 59.99,
    paymentMethod: 'Credit Card',
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'purch-3',
    userId: 'user-4',
    userName: 'Marcus Vance',
    userEmail: 'marcus.vance@icloud.com',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    bookId: 'book-3',
    bookTitle: 'History of Global Academic Libraries (1750–2025)',
    bookCover: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600',
    amount: 34.50,
    paymentMethod: 'Apple Pay',
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'purch-4',
    userId: 'user-5',
    userName: 'Sophia Chen',
    userEmail: 'sophia.chen@meta.com',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    bookId: 'book-4',
    bookTitle: 'Lytton to Maulana Azad Library: Vision and Mission',
    bookCover: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600',
    amount: 44.99,
    paymentMethod: 'Facebook Pay',
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
  },
];

export let bookmarksStore: Bookmark[] = [
  {
    id: 'bm-1',
    userId: 'user-2',
    bookId: 'book-1',
    pageNumber: 3,
    title: 'Quantum Gates Note',
    note: 'Important formula for Hadamard transformation',
    createdAt: '2026-03-01T10:00:00Z',
  },
];

export let readingHistoryStore: ReadingHistory[] = [
  {
    id: 'rh-1',
    userId: 'user-2',
    bookId: 'book-1',
    lastPage: 3,
    totalPages: 8,
    progressPercent: 37.5,
    updatedAt: '2026-03-01T10:30:00Z',
  },
];
